<?php
/**
 * Error handler version for web based modules
 */

namespace api\modules\v1\components;


/**
 * ErrorHandler
 * @package bedezign\yii2\audit\components\web
 */
class ErrorHandler extends \bedezign\yii2\audit\components\web\ErrorHandler
{
    public $errorAction = 'v1/auth/error';

    public function init()
    {

        parent::init(); // TODO: Change the autogenerated stub
    }
}